# Generated by Django 4.2.2 on 2023-07-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=30)),
                ("phone", models.CharField(max_length=15)),
                ("dsg", models.CharField(max_length=20)),
                ("salary", models.IntegerField()),
                (
                    "city",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                (
                    "state",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
            ],
        ),
    ]
